### ISSUE TITLE
Specification of which decile charts to generate

### ISSUE THREAD

**Issue by ccunningham101** [opensafely-actions/deciles-chart-action#4]
The current system will generate a decile chart for every file matching [this ](https://github.com/opensafely-actions/deciles-chart-action/blob/main/deciles_chart/core.py#L12) measure regex
Users may want to be able to provide
1. A more granular regex/glob specification (such as only measures files that contain the word "practice" in them)
2. Configuration information for individual or groups of charts (i.e. all measures with qof in the filename will have a ylabel of "Percentage" whereas others will have "Rate") 
    - Some of this information may not be easily parsable from the measures file name, so we could provide it in the yaml configuration

Per file:
```
qof:
    input_file: "measure_qof_practice_rate.csv"
    title: "QOF Achievement by Deciles"
    ylabel: "Percentage"
ssri:
    input_file: "measure_ssri_practice_rate.csv"
    title: "SSRI Use by Decile"
    ylabel: "Rate"
```

or 

To allow a combo of per-file and group with regex 
For regex could
1. Have internal code to parse the measure filename to determine parameters that would not be the same for the whole group (slightly different titles)
2. If that is not possible, it may be easier to have code to generate the yaml configuration or just require per-file specification
```
qof:
    input_file: "measure_qof_*_rate.csv"
    ylabel: "Percentage"
ssri:
    input_file: "measure_ssri_practice_rate.csv"
    title: "SSRI Use by Decile"
    ylabel: "Rate"
```

**Comment by ccunningham101** [comment]
I agree with all of the above, thanks for the clear explanation!
Two more configuration options that we have seen in repositories that use deciles charts are vertical plotlines to denote important dates and allow for scaling of the y-axis. I did very quick implementations on Milan's blood pressure repository

1.  [Add vertical plotlines to denote important dates](https://github.com/opensafely/blood-pressure-sro/pull/26/files)

- I went with manually user specified dates rather than anything programmatic as I don't think it would be easy to decipher a plot with many more than 4 or so lines
- It is currently missing any checks to see whether the values are within the visible range of the x-axis 
- It currently assumes that the y axis is a date and casts the user input to a date- a more flexible option could require the user to specify the type in the config, and check that the type specified matches the y axis 

3.  [Allow for scaling of the y-axis](https://github.com/opensafely/blood-pressure-sro/pull/28)
I started with 1.05*max val until Milan pointed out that the [autoscale](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.autoscale.html) function existed, but we were seeing strange results on the server. Could have been an issue with where/how I was invoking it, but may require further debugging

**Comment by LFISHER7** [comment]
#22 describes an additional configuration option. I think this along with the title and axis labels would be a good first step for some customisation

**Comment by iaindillingham** [comment]
This is a good opportunity to think about how the `config` key looks. #18 and #21 propose/add configuration. With this configuration, an invocation of deciles-charts could look like this:

```yaml
generate_deciles_charts:
  run: >
    python:latest analysis/deciles_charts.py
      --input-files output/measure_*.csv
      --output-dir output
  config:
    show_outer_percentiles: true
    outputs:
      - tables
      - charts
  needs: [generate_measures]
  outputs:
    moderately_sensitive:
      deciles_tables: output/deciles_table_*.png
      deciles_charts: output/deciles_chart_*.png
```

However, this invocation could be confusing: do we show outer percentiles on the tables _and_ charts? If the table isn't for presentation, then is "show" the best verb?

An alternative invocation of deciles-charts could look like this:

```yaml
generate_deciles_charts:
  run: >
    python:latest analysis/deciles_charts.py
      --input-files output/measure_*.csv
      --output-dir output
  config:
    tables:
      output: true
      outer_percentiles: false
    charts:
      output: true
      outer_percentiles: false
      encoding:
        x:
          title: "Date"
          scale:
            domain: ["min", "max"]
        y:
          title: "Value"
          scale:
            domain: [0, "max"]
  needs: [generate_measures]
  outputs:
    moderately_sensitive:
      deciles_tables: output/deciles_table_*.png
      deciles_charts: output/deciles_chart_*.png
```

I've given default values, so the `config` key is unnecessary. You're probably wondering about the `encoding` key. Well, I'd like to propose using a subset of [Vega-Lite][] for configuring deciles charts. Essentially, the `charts` key could contain a subset of a [single view specification][1].

I'd really appreciate your feedback on ☝🏻, because although we can refactor configuration, this gets harder and harder as we add more. Ideally, we'd like to make the `config` key:

* unnecessary for the majority of cases - "no config" tending to "low config"
* expressive - it should allow us to express many possible configurations, even those we haven't thought of yet 🙂
* "intuitive" - you shouldn't have to think too hard about what the configuration is configuring

I'm going to create a new issue for "Add vertical plotlines to show important dates", because this feels like a non-trivial amount of work. It would be useful to discuss examples, too.

[Vega-Lite]: https://vega.github.io/vega-lite/
[1]: https://vega.github.io/vega-lite/docs/spec.html#single
